/// The country to search for articles.
enum NewsCountry {
  unitedArabEmirates._('ae'),
  argentina._('ar'),
  austria._('at'),
  australia._('au'),
  belgium._('be'),
  bulgaria._('bg'),
  brazil._('br'),
  canada._('ca'),
  switzerland._('ch'),
  china._('cn'),
  colombia._('co'),
  cuba._('cu'),
  czechia._('cz'),
  germany._('de'),
  egypt._('eg'),
  france._('fr'),
  greatBritain._('gb'),
  greece._('gr'),
  hongKong._('hk'),
  hungary._('hu'),
  indonesia._('id'),
  ireland._('ie'),
  israel._('il'),
  india._('in'),
  italy._('it'),
  japan._('jp'),
  southKorea._('kr'),
  lithuania._('lt'),
  latvia._('lv'),
  morocco._('ma'),
  mexico._('mx'),
  malaysia._('my'),
  nigeria._('ng'),
  netherlands._('nl'),
  norway._('no'),
  newZealand._('nz'),
  philippines._('ph'),
  poland._('pl'),
  portugal._('pt'),
  romania._('ro'),
  serbia._('rs'),
  russia._('ru'),
  saudiArabia._('sa'),
  sweden._('se'),
  singapore._('sg'),
  slovenia._('si'),
  slovakia._('sk'),
  thailand._('th'),
  turkey._('tr'),
  taiwan._('tw'),
  ukraine._('ua'),
  unitedStates._('us'),
  venezuela._('ve'),
  southAfrica._('za');

  const NewsCountry._(this._value);
  final String _value;

  @override
  String toString() => _value;
}
