name: app_ui
description: App UI package
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  app_model:
    path: ../app_model
  cached_network_image: ^3.3.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  mockito: ^5.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/images/