name: app_model
description: "Dart package to hold app models"
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.3.4
  json_serializable: ^6.7.0
